site_name: AustralianHPC.org
site_url: https://australianhpc.org/

pages:
        - Home: index.md
        - Sites: sites.md
        - Systems: systems.md
        - Resources: resources.md

theme:
          name: 'material'
